### ISSUE TITLE
Compilation gives warning about unused variable

### ISSUE THREAD

**Issue by timtashpulatov** [sergev/mfmdisk#1]
amiga.c: In function ‘mfm_read_sector_amiga’:
amiga.c:151:16: warning: variable ‘label’ set but not used [-Wunused-but-set-variable]
  unsigned long label[4], header_sum, data_sum;
                ^~~~~

**Comment by sergev** [comment]
Fixed in 75a29db0776b31c9afe16fc4fea28d0006e48fcb.
Thanks for bug report.
